package com.xydq.mall.ad.dao.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mall_banner
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MallBanner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_banner.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   banner图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_banner.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     * Database Column Remarks:
     *   跳转地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_banner.link_url
     *
     * @mbg.generated
     */
    private String linkUrl;

    /**
     * Database Column Remarks:
     *   banner顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_banner.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   是否可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_banner.enable
     *
     * @mbg.generated
     */
    private Boolean enable;

    /**
     * Database Column Remarks:
     *   新增时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_banner.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_banner.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   删除逻辑
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_banner.deleted_id
     *
     * @mbg.generated
     */
    private Integer deletedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_banner.id
     *
     * @return the value of mall_banner.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_banner.id
     *
     * @param id the value for mall_banner.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_banner.pic_url
     *
     * @return the value of mall_banner.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_banner.pic_url
     *
     * @param picUrl the value for mall_banner.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_banner.link_url
     *
     * @return the value of mall_banner.link_url
     *
     * @mbg.generated
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_banner.link_url
     *
     * @param linkUrl the value for mall_banner.link_url
     *
     * @mbg.generated
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_banner.sort
     *
     * @return the value of mall_banner.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_banner.sort
     *
     * @param sort the value for mall_banner.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_banner.enable
     *
     * @return the value of mall_banner.enable
     *
     * @mbg.generated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_banner.enable
     *
     * @param enable the value for mall_banner.enable
     *
     * @mbg.generated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_banner.add_time
     *
     * @return the value of mall_banner.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_banner.add_time
     *
     * @param addTime the value for mall_banner.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_banner.update_time
     *
     * @return the value of mall_banner.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_banner.update_time
     *
     * @param updateTime the value for mall_banner.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_banner.deleted_id
     *
     * @return the value of mall_banner.deleted_id
     *
     * @mbg.generated
     */
    public Integer getDeletedId() {
        return deletedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_banner.deleted_id
     *
     * @param deletedId the value for mall_banner.deleted_id
     *
     * @mbg.generated
     */
    public void setDeletedId(Integer deletedId) {
        this.deletedId = deletedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", picUrl=").append(picUrl);
        sb.append(", linkUrl=").append(linkUrl);
        sb.append(", sort=").append(sort);
        sb.append(", enable=").append(enable);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deletedId=").append(deletedId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MallBanner other = (MallBanner) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPicUrl() == null ? other.getPicUrl() == null : this.getPicUrl().equals(other.getPicUrl()))
            && (this.getLinkUrl() == null ? other.getLinkUrl() == null : this.getLinkUrl().equals(other.getLinkUrl()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeletedId() == null ? other.getDeletedId() == null : this.getDeletedId().equals(other.getDeletedId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPicUrl() == null) ? 0 : getPicUrl().hashCode());
        result = prime * result + ((getLinkUrl() == null) ? 0 : getLinkUrl().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeletedId() == null) ? 0 : getDeletedId().hashCode());
        return result;
    }
}