package com.xydq.mall.goods.dao.mapper;

import com.xydq.mall.goods.dao.domain.MallCatagory;
import com.xydq.mall.goods.dao.domain.MallCatagoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallCatagoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    long countByExample(MallCatagoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    int deleteByExample(MallCatagoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    int insert(MallCatagory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    int insertSelective(MallCatagory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    List<MallCatagory> selectByExample(MallCatagoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    MallCatagory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallCatagory record, @Param("example") MallCatagoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallCatagory record, @Param("example") MallCatagoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallCatagory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_catagory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallCatagory record);
}