package com.xydq.mall.goods.dao.mapper;

import com.xydq.mall.goods.dao.domain.MallGoodsDetail;
import com.xydq.mall.goods.dao.domain.MallGoodsDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallGoodsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    long countByExample(MallGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    int deleteByExample(MallGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    int insert(MallGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    int insertSelective(MallGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    List<MallGoodsDetail> selectByExample(MallGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    MallGoodsDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallGoodsDetail record, @Param("example") MallGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallGoodsDetail record, @Param("example") MallGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallGoodsDetail record);
}