package com.xydq.mall.goods.dao.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mall_goods
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MallGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     * Database Column Remarks:
     *   类目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   品牌ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.brand_id
     *
     * @mbg.generated
     */
    private Integer brandId;

    /**
     * Database Column Remarks:
     *   商品简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.brief
     *
     * @mbg.generated
     */
    private String brief;

    /**
     * Database Column Remarks:
     *   商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     * Database Column Remarks:
     *   促销价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.sale_price
     *
     * @mbg.generated
     */
    private Long salePrice;

    /**
     * Database Column Remarks:
     *   商品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.goods_pic
     *
     * @mbg.generated
     */
    private String goodsPic;

    /**
     * Database Column Remarks:
     *   是否为热门商品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.hot_goods
     *
     * @mbg.generated
     */
    private Boolean hotGoods;

    /**
     * Database Column Remarks:
     *   库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.remain_num
     *
     * @mbg.generated
     */
    private Integer remainNum;

    /**
     * Database Column Remarks:
     *   是否上架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.on_sale
     *
     * @mbg.generated
     */
    private Boolean onSale;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   新增时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   删除逻辑
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_goods.deleted_id
     *
     * @mbg.generated
     */
    private Integer deletedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.id
     *
     * @return the value of mall_goods.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.id
     *
     * @param id the value for mall_goods.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.goods_name
     *
     * @return the value of mall_goods.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.goods_name
     *
     * @param goodsName the value for mall_goods.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.category_id
     *
     * @return the value of mall_goods.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.category_id
     *
     * @param categoryId the value for mall_goods.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.brand_id
     *
     * @return the value of mall_goods.brand_id
     *
     * @mbg.generated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.brand_id
     *
     * @param brandId the value for mall_goods.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.brief
     *
     * @return the value of mall_goods.brief
     *
     * @mbg.generated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.brief
     *
     * @param brief the value for mall_goods.brief
     *
     * @mbg.generated
     */
    public void setBrief(String brief) {
        this.brief = brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.price
     *
     * @return the value of mall_goods.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.price
     *
     * @param price the value for mall_goods.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.sale_price
     *
     * @return the value of mall_goods.sale_price
     *
     * @mbg.generated
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.sale_price
     *
     * @param salePrice the value for mall_goods.sale_price
     *
     * @mbg.generated
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.goods_pic
     *
     * @return the value of mall_goods.goods_pic
     *
     * @mbg.generated
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.goods_pic
     *
     * @param goodsPic the value for mall_goods.goods_pic
     *
     * @mbg.generated
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.hot_goods
     *
     * @return the value of mall_goods.hot_goods
     *
     * @mbg.generated
     */
    public Boolean getHotGoods() {
        return hotGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.hot_goods
     *
     * @param hotGoods the value for mall_goods.hot_goods
     *
     * @mbg.generated
     */
    public void setHotGoods(Boolean hotGoods) {
        this.hotGoods = hotGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.remain_num
     *
     * @return the value of mall_goods.remain_num
     *
     * @mbg.generated
     */
    public Integer getRemainNum() {
        return remainNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.remain_num
     *
     * @param remainNum the value for mall_goods.remain_num
     *
     * @mbg.generated
     */
    public void setRemainNum(Integer remainNum) {
        this.remainNum = remainNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.on_sale
     *
     * @return the value of mall_goods.on_sale
     *
     * @mbg.generated
     */
    public Boolean getOnSale() {
        return onSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.on_sale
     *
     * @param onSale the value for mall_goods.on_sale
     *
     * @mbg.generated
     */
    public void setOnSale(Boolean onSale) {
        this.onSale = onSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.sort
     *
     * @return the value of mall_goods.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.sort
     *
     * @param sort the value for mall_goods.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.add_time
     *
     * @return the value of mall_goods.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.add_time
     *
     * @param addTime the value for mall_goods.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.update_time
     *
     * @return the value of mall_goods.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.update_time
     *
     * @param updateTime the value for mall_goods.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_goods.deleted_id
     *
     * @return the value of mall_goods.deleted_id
     *
     * @mbg.generated
     */
    public Integer getDeletedId() {
        return deletedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_goods.deleted_id
     *
     * @param deletedId the value for mall_goods.deleted_id
     *
     * @mbg.generated
     */
    public void setDeletedId(Integer deletedId) {
        this.deletedId = deletedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", brandId=").append(brandId);
        sb.append(", brief=").append(brief);
        sb.append(", price=").append(price);
        sb.append(", salePrice=").append(salePrice);
        sb.append(", goodsPic=").append(goodsPic);
        sb.append(", hotGoods=").append(hotGoods);
        sb.append(", remainNum=").append(remainNum);
        sb.append(", onSale=").append(onSale);
        sb.append(", sort=").append(sort);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deletedId=").append(deletedId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MallGoods other = (MallGoods) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGoodsName() == null ? other.getGoodsName() == null : this.getGoodsName().equals(other.getGoodsName()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getBrandId() == null ? other.getBrandId() == null : this.getBrandId().equals(other.getBrandId()))
            && (this.getBrief() == null ? other.getBrief() == null : this.getBrief().equals(other.getBrief()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getSalePrice() == null ? other.getSalePrice() == null : this.getSalePrice().equals(other.getSalePrice()))
            && (this.getGoodsPic() == null ? other.getGoodsPic() == null : this.getGoodsPic().equals(other.getGoodsPic()))
            && (this.getHotGoods() == null ? other.getHotGoods() == null : this.getHotGoods().equals(other.getHotGoods()))
            && (this.getRemainNum() == null ? other.getRemainNum() == null : this.getRemainNum().equals(other.getRemainNum()))
            && (this.getOnSale() == null ? other.getOnSale() == null : this.getOnSale().equals(other.getOnSale()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeletedId() == null ? other.getDeletedId() == null : this.getDeletedId().equals(other.getDeletedId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGoodsName() == null) ? 0 : getGoodsName().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getBrandId() == null) ? 0 : getBrandId().hashCode());
        result = prime * result + ((getBrief() == null) ? 0 : getBrief().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getSalePrice() == null) ? 0 : getSalePrice().hashCode());
        result = prime * result + ((getGoodsPic() == null) ? 0 : getGoodsPic().hashCode());
        result = prime * result + ((getHotGoods() == null) ? 0 : getHotGoods().hashCode());
        result = prime * result + ((getRemainNum() == null) ? 0 : getRemainNum().hashCode());
        result = prime * result + ((getOnSale() == null) ? 0 : getOnSale().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeletedId() == null) ? 0 : getDeletedId().hashCode());
        return result;
    }
}