package com.xydq.mall.ad.dao.mapper;

import com.xydq.mall.ad.dao.domain.MallBanner;
import com.xydq.mall.ad.dao.domain.MallBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    long countByExample(MallBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    int deleteByExample(MallBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    int insert(MallBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    int insertSelective(MallBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    List<MallBanner> selectByExample(MallBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    MallBanner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallBanner record, @Param("example") MallBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallBanner record, @Param("example") MallBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_banner
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallBanner record);
}